# Generated by Django 6.0.1 on 2026-01-28 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='회사명')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='주소')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='전화번호')),
                ('website', models.URLField(blank=True, verbose_name='웹사이트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '제조회사',
                'verbose_name_plural': '제조회사',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Efficacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='효능명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '효능',
                'verbose_name_plural': '효능',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='성분명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '성분',
                'verbose_name_plural': '성분',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('dosage', models.TextField(blank=True, verbose_name='용법용량')),
                ('precautions', models.TextField(blank=True, verbose_name='주의사항')),
                ('side_effects', models.TextField(blank=True, verbose_name='부작용')),
                ('storage', models.CharField(blank=True, max_length=500, verbose_name='보관방법')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='허가일자')),
                ('approval_number', models.CharField(blank=True, max_length=100, verbose_name='허가번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicines.company', verbose_name='제조회사')),
                ('efficacies', models.ManyToManyField(related_name='medicines', to='medicines.efficacy', verbose_name='효능')),
                ('ingredients', models.ManyToManyField(related_name='medicines', to='medicines.ingredient', verbose_name='성분')),
            ],
            options={
                'verbose_name': '의약품',
                'verbose_name_plural': '의약품',
                'ordering': ['-created_at'],
            },
        ),
    ]
